class CreateMarcas < ActiveRecord::Migration[5.1]
  def change
    create_table :marcas do |t|
      t.string :nome

      t.timestamps
    end

    Marca.create(id: 1, nome: "CHEVROLET");
    Marca.create(id: 2, nome: "VOLKSWAGEN");
    Marca.create(id: 3, nome: "FIAT");
    Marca.create(id: 4, nome: "MERCEDES-BENZ");
    Marca.create(id: 5, nome: "CITROEN");
    Marca.create(id: 6, nome: "CHANA");
    Marca.create(id: 7, nome: "HONDA");
    Marca.create(id: 8, nome: "SUBARU");
    Marca.create(id: 10, nome: "FERRARI");
    Marca.create(id: 11, nome: "BUGATTI");
    Marca.create(id: 12, nome: "LAMBORGHINI");
    Marca.create(id: 13, nome: "FORD");
    Marca.create(id: 14, nome: "HYUNDAI");
    Marca.create(id: 15, nome: "JAC");
    Marca.create(id: 16, nome: "KIA");
    Marca.create(id: 17, nome: "GURGEL");
    Marca.create(id: 18, nome: "DODGE");
    Marca.create(id: 19, nome: "CHRYSLER");
    Marca.create(id: 20, nome: "BENTLEY");
    Marca.create(id: 21, nome: "SSANGYONG");
    Marca.create(id: 22, nome: "PEUGEOT");
    Marca.create(id: 23, nome: "TOYOTA");
    Marca.create(id: 24, nome: "RENAULT");
    Marca.create(id: 25, nome: "ACURA");
    Marca.create(id: 26, nome: "ADAMO");
    Marca.create(id: 27, nome: "AGRALE");
    Marca.create(id: 28, nome: "ALFA ROMEO");
    Marca.create(id: 29, nome: "AMERICAR");
    Marca.create(id: 31, nome: "ASTON MARTIN");
    Marca.create(id: 32, nome: "AUDI");
    Marca.create(id: 34, nome: "BEACH");
    Marca.create(id: 35, nome: "BIANCO");
    Marca.create(id: 36, nome: "BMW");
    Marca.create(id: 37, nome: "BORGWARD");
    Marca.create(id: 38, nome: "BRILLIANCE");
    Marca.create(id: 41, nome: "BUICK");
    Marca.create(id: 42, nome: "CBT");
    Marca.create(id: 43, nome: "NISSAN");
    Marca.create(id: 44, nome: "CHAMONIX");
    Marca.create(id: 46, nome: "CHEDA");
    Marca.create(id: 47, nome: "CHERY");
    Marca.create(id: 48, nome: "CORD");
    Marca.create(id: 49, nome: "COYOTE");
    Marca.create(id: 50, nome: "CROSS LANDER");
    Marca.create(id: 51, nome: "DAEWOO");
    Marca.create(id: 52, nome: "DAIHATSU");
    Marca.create(id: 53, nome: "VOLVO");
    Marca.create(id: 54, nome: "DE SOTO");
    Marca.create(id: 55, nome: "DETOMAZO");
    Marca.create(id: 56, nome: "DELOREAN");
    Marca.create(id: 57, nome: "DKW-VEMAG");
    Marca.create(id: 59, nome: "SUZUKI");
    Marca.create(id: 60, nome: "EAGLE");
    Marca.create(id: 61, nome: "EFFA");
    Marca.create(id: 63, nome: "ENGESA");
    Marca.create(id: 64, nome: "ENVEMO");
    Marca.create(id: 65, nome: "FARUS");
    Marca.create(id: 66, nome: "FERCAR");
    Marca.create(id: 68, nome: "FNM");
    Marca.create(id: 69, nome: "PONTIAC");
    Marca.create(id: 70, nome: "PORSCHE");
    Marca.create(id: 72, nome: "GEO");
    Marca.create(id: 74, nome: "GRANCAR");
    Marca.create(id: 75, nome: "GREAT WALL");
    Marca.create(id: 76, nome: "HAFEI");
    Marca.create(id: 78, nome: "HOFSTETTER");
    Marca.create(id: 79, nome: "HUDSON");
    Marca.create(id: 80, nome: "HUMMER");
    Marca.create(id: 82, nome: "INFINITI");
    Marca.create(id: 83, nome: "INTERNATIONAL");
    Marca.create(id: 86, nome: "JAGUAR");
    Marca.create(id: 87, nome: "JEEP");
    Marca.create(id: 88, nome: "JINBEI");
    Marca.create(id: 89, nome: "JPX");
    Marca.create(id: 90, nome: "KAISER");
    Marca.create(id: 91, nome: "KOENIGSEGG");
    Marca.create(id: 92, nome: "LAUTOMOBILE");
    Marca.create(id: 93, nome: "LAUTOCRAFT");
    Marca.create(id: 94, nome: "LADA");
    Marca.create(id: 95, nome: "LANCIA");
    Marca.create(id: 96, nome: "LAND ROVER");
    Marca.create(id: 97, nome: "LEXUS");
    Marca.create(id: 98, nome: "LIFAN");
    Marca.create(id: 99, nome: "LINCOLN");
    Marca.create(id: 100, nome: "LOBINI");
    Marca.create(id: 101, nome: "LOTUS");
    Marca.create(id: 102, nome: "MAHINDRA");
    Marca.create(id: 104, nome: "MASERATI");
    Marca.create(id: 106, nome: "MATRA");
    Marca.create(id: 107, nome: "MAYBACH");
    Marca.create(id: 108, nome: "MAZDA");
    Marca.create(id: 109, nome: "MENON");
    Marca.create(id: 110, nome: "MERCURY");
    Marca.create(id: 111, nome: "MITSUBISHI");
    Marca.create(id: 112, nome: "MG");
    Marca.create(id: 113, nome: "MINI");
    Marca.create(id: 114, nome: "MIURA");
    Marca.create(id: 115, nome: "MORRIS");
    Marca.create(id: 116, nome: "MP LAFER");
    Marca.create(id: 117, nome: "MPLM");
    Marca.create(id: 118, nome: "NEWTRACK");
    Marca.create(id: 119, nome: "NISSIN");
    Marca.create(id: 120, nome: "OLDSMOBILE");
    Marca.create(id: 121, nome: "PAG");
    Marca.create(id: 122, nome: "PAGANI");
    Marca.create(id: 123, nome: "PLYMOUTH");
    Marca.create(id: 124, nome: "PUMA");
    Marca.create(id: 125, nome: "RENO");
    Marca.create(id: 126, nome: "REVA-I");
    Marca.create(id: 127, nome: "ROLLS-ROYCE");
    Marca.create(id: 129, nome: "ROMI");
    Marca.create(id: 130, nome: "SEAT");
    Marca.create(id: 131, nome: "UTILITARIOS AGRICOLAS");
    Marca.create(id: 132, nome: "SHINERAY");
    Marca.create(id: 137, nome: "SAAB");
    Marca.create(id: 139, nome: "SHORT");
    Marca.create(id: 141, nome: "SIMCA");
    Marca.create(id: 142, nome: "SMART");
    Marca.create(id: 143, nome: "SPYKER");
    Marca.create(id: 144, nome: "STANDARD");
    Marca.create(id: 145, nome: "STUDEBAKER");
    Marca.create(id: 146, nome: "TAC");
    Marca.create(id: 147, nome: "TANGER");
    Marca.create(id: 148, nome: "TRIUMPH");
    Marca.create(id: 149, nome: "TROLLER");
    Marca.create(id: 150, nome: "UNIMOG");
    Marca.create(id: 154, nome: "WIESMANN");
    Marca.create(id: 155, nome: "CADILLAC");
    Marca.create(id: 156, nome: "AM GEN");
    Marca.create(id: 157, nome: "BUGGY");
    Marca.create(id: 158, nome: "WILLYS OVERLAND");
    Marca.create(id: 161, nome: "KASEA");
    Marca.create(id: 162, nome: "SATURN");
    Marca.create(id: 163, nome: "SWELL MINI");
    Marca.create(id: 175, nome: "SKODA");
    Marca.create(id: 239, nome: "KARMANN GHIA");
    Marca.create(id: 254, nome: "KART");
    Marca.create(id: 258, nome: "HANOMAG");
    Marca.create(id: 261, nome: "OUTROS");
    Marca.create(id: 265, nome: "HILLMAN");
    Marca.create(id: 288, nome: "HRG");
    Marca.create(id: 295, nome: "GAIOLA");
    Marca.create(id: 338, nome: "TATA");
    Marca.create(id: 341, nome: "DITALLY");
    Marca.create(id: 345, nome: "RELY");
    Marca.create(id: 346, nome: "MCLAREN");
    Marca.create(id: 534, nome: "GEELY");
  end
end
