class CreateBancos < ActiveRecord::Migration[5.1]
  def change
    create_table :bancos do |t|
      t.string :codigo, limit: 10
      t.string :nome
      t.string :sigla, limit: 30

      t.timestamps
    end

    Banco.create(id: 1, codigo:"1", nome: "Banco do Brasil",	sigla: "BB");
    Banco.create(id: 2, codigo:"104", nome: "Caixa Econômica Federal",	sigla: "CEF");
    Banco.create(id: 3, codigo:"237", nome: "Bradesco",	sigla: "Bradesco");
    Banco.create(id: 4, codigo:"341", nome: "Itaú Unibanco",	sigla: "Itaú");
    Banco.create(id: 5, codigo:"33", nome: "Banco Santander",	sigla: "Santander");
    Banco.create(id: 6, codigo:"473", nome: "Banco Caixa Geral - Brasil", sigla: "BCG Brasil");
    Banco.create(id: 7, codigo:"745", nome: "Banco Citibank",	sigla: "Citibank");
    Banco.create(id: 8, codigo:"756", nome: "Banco Cooperativo do Brasil - BANCOOB",	sigla: "BANCOOB");
    Banco.create(id: 9, codigo:"748", nome: "Banco Cooperativo Sicredi - BANSICREDI",	sigla: "SICREDI");
    Banco.create(id: 10, codigo:"637", nome: "Banco Sofisa",	sigla: "Sofisa");
    Banco.create(id: 11, codigo:"212", nome: "Banco Original",	sigla: "Original");
    Banco.create(id: 12, codigo:"260", nome: "Nu Pagamentos S.A",	sigla: "Nubank");
    Banco.create(id: 13, codigo:"409", nome: "Unibanco", sigla: "Unibanco");
    Banco.create(id: 14, codigo:"3", nome: "Banco da Amazônia",	sigla: "BASA");
    Banco.create(id: 15, codigo:"4", nome: "Banco do Nordeste do Brasil",	sigla: "BNB");
    Banco.create(id: 16, codigo:"7", nome: "Banco Nacional de Desenvolvimento Econômico e Social",	sigla: "BNDES");
    Banco.create(id: 17, codigo:"46", nome: "Banco Regional de Desenvolvimento do Extremo Sul",	sigla: "BRDE");
    Banco.create(id: 18, codigo:"23", nome: "Banco de Desenvolvimento de Minas Gerais",	sigla: "BDMG");
    Banco.create(id: 19, codigo:"70", nome: "Banco de Brasília",	sigla: "BRB");
    Banco.create(id: 20, codigo:"47", nome: "Banco do Estado de Sergipe",	sigla: "Banese");
    Banco.create(id: 21, codigo:"21", nome: "Banco do Estado do Espírito Santo",	sigla: "Banestes");
    Banco.create(id: 22, codigo:"37", nome: "Banco do Estado do Pará",	sigla: "Banpará");
    Banco.create(id: 23, codigo:"41", nome: "Banco do Estado do Rio Grande do Sul",	sigla: "Banrisul");
    Banco.create(id: 24, codigo:"75", nome: "Banco ABN Amro S.A.",	sigla: "ABN");
    Banco.create(id: 25, codigo:"25", nome: "Banco Alfa",	sigla: "Alfa");
    Banco.create(id: 26, codigo:"719", nome: "Banco Banif",	sigla: "Banif");
    Banco.create(id: 27, codigo:"107", nome: "Banco BBM",	sigla: "BBM");
    Banco.create(id: 28, codigo:"318", nome: "Banco BMG",	sigla: "BMG");
    Banco.create(id: 29, codigo:"218", nome: "Banco Bonsucesso",	sigla: "Bonsucesso");
    Banco.create(id: 30, codigo:"208", nome: "Banco BTG Pactual",	sigla: "BTG");
    Banco.create(id: 31, codigo:"263", nome: "Banco Cacique",	sigla: "Cacique");
    Banco.create(id: 32, codigo:"721", nome: "Banco Credibel",	sigla: "Credibel");
    Banco.create(id: 33, codigo:"505", nome: "Banco Credit Suisse	Credit", sigla: "Suisse");
    Banco.create(id: 34, codigo:"265", nome: "Banco Fator",	sigla: "Fator");
    Banco.create(id: 35, codigo:"224", nome: "Banco Fibra",	sigla: "Fibra");
    Banco.create(id: 36, codigo:"121", nome: "Agibank",	sigla: "Agibank");
    Banco.create(id: 37, codigo:"612", nome: "Banco Guanabara",	sigla: "Guanabara");
    Banco.create(id: 38, codigo:"604", nome: "Banco Industrial do Brasil",	sigla: "BI");
    Banco.create(id: 39, codigo:"320", nome: "Banco Industrial e Comercial",	sigla: "BICBANCO");
    Banco.create(id: 40, codigo:"653", nome: "Banco Indusval	BI", sigla: "P");
    Banco.create(id: 41, codigo:"77", nome: "Banco Inter	Banco", sigla: "Inter");
    Banco.create(id: 42, codigo:"184", nome: "Banco Itaú BBA	Itaú", sigla: "BBA");
    Banco.create(id: 43, codigo:"479", nome: "Banco ItaúBank",	sigla: "ItaúBank");
    Banco.create(id: 44, codigo:"M09", nome: "Banco Itaucred Financiamentos	Itaucred", sigla: "Financiamentos");
    Banco.create(id: 45, codigo:"389", nome: "Banco Mercantil do Brasil",	sigla: "BMB");
    Banco.create(id: 46, codigo:"746", nome: "Banco Modal",	sigla: "Modal");
    Banco.create(id: 47, codigo:"738", nome: "Banco Morada",	sigla: "Morada");
    Banco.create(id: 48, codigo:"623", nome: "Banco Pan",	sigla: "Pan");
    Banco.create(id: 49, codigo:"611", nome: "Banco Paulista",	sigla: "Paulista");
    Banco.create(id: 50, codigo:"643", nome: "Banco Pine",	sigla: "Pine");
    Banco.create(id: 51, codigo:"654", nome: "Banco Renner",	sigla: "Renner");
    Banco.create(id: 52, codigo:"741", nome: "Banco Ribeirão Preto",	sigla: "BRP");
    Banco.create(id: 53, codigo:"422", nome: "Banco Safra",	sigla: "Safra");
    Banco.create(id: 54, codigo:"82", nome: "Banco Topázio",	sigla: "Topázio");
    Banco.create(id: 55, codigo:"655", nome: "Banco Votorantim",	sigla: "BV");
    Banco.create(id: 56, codigo:"136", nome: "Unicred",	sigla: "UNICRED");
    Banco.create(id: 57, codigo:"356", nome: "ABN AMRO Bank", sigla:	"");
    Banco.create(id: 58, codigo:"215", nome: "Banco América do Sul",	sigla: "BAS");
    Banco.create(id: 59, codigo:"625", nome: "Banco Araucária", sigla: 	"");
    Banco.create(id: 60, codigo:"226", nome: "Banco Auxiliar", sigla: 	"");
    Banco.create(id: 61, codigo:"230", nome: "Banco Bandeirantes", sigla: 	"");
    Banco.create(id: 62, codigo:"184", nome: "Banco BBA", sigla: 	"");
    Banco.create(id: 63, codigo:"739", nome: "Banco BGN", sigla: 	"");
    Banco.create(id: 64, codigo:"641", nome: "Banco Bilbao Vizcaya Argentaria",	sigla: "BBVA");
    Banco.create(id: 65, codigo:"394", nome: "Banco BMC", sigla:	"");
    Banco.create(id: 66, codigo:"388", nome: "Banco BMD", sigla: 	"");
    Banco.create(id: 67, codigo:"231", nome: "Banco Boavista", sigla: 	"");
    Banco.create(id: 68, codigo:"351", nome: "Banco Bozano Simonsen", sigla: 	"");
    Banco.create(id: 69, codigo:"282", nome: "Banco Brasileiro Comercial",	sigla: "BBC");
    Banco.create(id: 70, codigo:"244", nome: "Banco Cidade", sigla: 	"");
    Banco.create(id: 71, codigo:"282", nome: "Banco Comercial Bancesa",	sigla: "Bancesa");
    Banco.create(id: 72, codigo:"106", nome: "Banco Crefisul", sigla: 	"");
    Banco.create(id: 73, codigo:"229", nome: "Banco Cruzeiro do Sul", sigla: 	"");
    Banco.create(id: 74, codigo:"233", nome: "Banco da Capital", sigla:	"");
    Banco.create(id: 75, codigo:"314", nome: "Banco do Comércio e Indústria de São Paulo",	sigla: "Comind");
    Banco.create(id: 76, codigo:"291", nome: "Banco de Crédito Nacional",	sigla: "BCN");
    Banco.create(id: 77, codigo:"22", nome: "Banco de Crédito Real de Minas Gerais",	sigla: "Credireal");
    Banco.create(id: 78, codigo:"26", nome: "Banco do Estado do Acre",	sigla: "Banacre");
    Banco.create(id: 79, codigo:"20", nome: "Banco do Estado de Alagoas",	sigla: "Produban");
    Banco.create(id: 80, codigo:"635", nome: "Banco do Estado de Amapá",	sigla: "Banap");
    Banco.create(id: 81, codigo:"34", nome: "Banco do Estado do Amazonas",	sigla: "BEA");
    Banco.create(id: 82, codigo:"28", nome: "Banco do Estado da Bahia",	sigla: "Baneb");
    Banco.create(id: 83, codigo:"35", nome: "Banco do Estado do Ceará",	sigla: "BEC");
    Banco.create(id: 84, codigo:"31", nome: "Banco do Estado de Goiás",	sigla: "BEG");
    Banco.create(id: 85, codigo:"36", nome: "Banco do Estado do Maranhão",	sigla: "BEM");
    Banco.create(id: 86, codigo:"32", nome: "Banco do Estado de Mato Grosso",	sigla: "Bemat");
    Banco.create(id: 87, codigo:"48", nome: "Banco do Estado de Minas Gerais",	sigla: "Bemge");
    Banco.create(id: 88, codigo:"30", nome: "Banco do Estado da Paraíba",	sigla: "Paraiban");
    Banco.create(id: 89, codigo:"38", nome: "Banco do Estado do Paraná",	sigla: "Banestado");
    Banco.create(id: 90, codigo:"24", nome: "Banco do Estado de Pernambuco",	sigla: "Bandepe");
    Banco.create(id: 91, codigo:"39", nome: "Banco do Estado do Piauí",	sigla: "BEP");
    Banco.create(id: 92, codigo:"29", nome: "Banco do Estado do Rio de Janeiro",	sigla: "Banerj");
    Banco.create(id: 93, codigo:"43", nome: "Banco do Estado de Rio Grande do Norte",	sigla: "Bandern");
    Banco.create(id: 94, codigo:"59", nome: "Banco do Estado de Rondônia",	sigla: "Beron");
    Banco.create(id: 95, codigo:"645", nome: "Banco do Estado de Roraima",	sigla: "Baner");
    Banco.create(id: 96, codigo:"27", nome: "Banco do Estado de Santa Catarina",	sigla: "Besc");
    Banco.create(id: 97, codigo:"33", nome: "Banco do Estado de São Paulo",	sigla: "Banespa");
    Banco.create(id: 98, codigo:"334", nome: "Banco Econômico", sigla: 	"");
    Banco.create(id: 99, codigo:"245", nome: "Banco Empresarial", sigla: 	"");
    Banco.create(id: 100, codigo:"641", nome: "Banco Excel", sigla: 	"");
    Banco.create(id: 101, codigo:"338", nome: "Banco F. Barreto", sigla:	"");
    Banco.create(id: 102, codigo:"392", nome: "Banco Federal de Crédito", sigla:	"");
    Banco.create(id: 103, codigo:"434", nome: "Banco Fortaleza", sigla: 	"");
    Banco.create(id: 104, codigo:"505", nome: "Banco Garantia", sigla: 	"");
    Banco.create(id: 105, codigo:"710", nome: "Banco Hexabanco", sigla: 	"");
    Banco.create(id: 106, codigo:"228", nome: "Banco Icatu", sigla: 	"");
    Banco.create(id: 107, codigo:"722", nome: "Banco Interior de São Paulo", sigla: 	"");
    Banco.create(id: 108, codigo:"232", nome: "Banco Interpart", sigla: 	"");
    Banco.create(id: 109, codigo:"223", nome: "Banco Interunion", sigla: 	"");
    Banco.create(id: 110, codigo:"234", nome: "Banco Lavra", sigla: 	"");
    Banco.create(id: 111, codigo:"235", nome: "Banco Liberal", sigla: 	"");
    Banco.create(id: 112, codigo:"491", nome: "Banco Maisonnave", sigla: 	"");
    Banco.create(id: 113, codigo:"647", nome: "Banco Marka",	sigla: "Marka");
    Banco.create(id: 114, codigo:"206", nome: "Banco Martinelli", sigla: 	"");
    Banco.create(id: 115, codigo:"212", nome: "Banco Matone", sigla: 	"");
    Banco.create(id: 116, codigo:"344", nome: "Banco Mercantil de Pernambuco", sigla: 	"");
    Banco.create(id: 117, codigo:"392", nome: "Banco Mercantil de São Paulo", sigla: 	"");
    Banco.create(id: 118, codigo:"392", nome: "Banco Mercantil Finasa", sigla: 	"");
    Banco.create(id: 119, codigo:"392", nome: "Banco Meridional", sigla: 	"");
    Banco.create(id: 120, codigo:"504", nome: "Banco Multiplic", sigla: 	"");
    Banco.create(id: 121, codigo:"415", nome: "Banco Nacional", sigla: 	"");
    Banco.create(id: 122, codigo:"420", nome: "Banco Nacional do Norte",	sigla: "Banorte");
    Banco.create(id: 123, codigo:"735", nome: "Banco Neon",	sigla: "Neon");
    Banco.create(id: 124, codigo:"424", nome: "Banco Noroeste", sigla: 	"");
    Banco.create(id: 125, codigo:"45", nome: "Banco Opportunity", sigla: 	"");
    Banco.create(id: 126, codigo:"304", nome: "Banco Pontual", sigla: 	"");
    Banco.create(id: 127, codigo:"73", nome: "Banco Popular do Brasil",	sigla: "BPB");
    Banco.create(id: 128, codigo:"638", nome: "Banco Prosper", sigla: 	"");
    Banco.create(id: 129, codigo:"220", nome: "Banco Queiroz", sigla: 	"");
    Banco.create(id: 130, codigo:"275", nome: "Banco Real", sigla:	"");
    Banco.create(id: 131, codigo:"326", nome: "Banco Royal de Investimento", sigla: 	"");
    Banco.create(id: 132, codigo:"453", nome: "Banco Rural", sigla: 	"");
    Banco.create(id: 133, codigo:"702", nome: "Banco Santos", sigla: 	"");
    Banco.create(id: 134, codigo:"607", nome: "Banco Santos Neves", sigla:	"");
    Banco.create(id: 135, codigo:"251", nome: "Banco São Jorge", sigla:	"");
    Banco.create(id: 136, codigo:"347", nome: "Banco Sudameris", sigla: 	"");
    Banco.create(id: 137, codigo:"715", nome: "Banco Vega", sigla: 	"");
    Banco.create(id: 138, codigo:"219", nome: "Banco Zogbi",	sigla: "Zogbi");
    Banco.create(id: 139, codigo:"152", nome: "Caixa Econômica do Estado de Goiás",	sigla: "Caixego");
    Banco.create(id: 140, codigo:"150", nome: "Caixa Econômica do Estado de Minas Gerais",	sigla: "MinasCaixa");
    Banco.create(id: 141, codigo:"153", nome: "Caixa Econômica Estadual do Rio Grande do Sul",	sigla: "CEERS");
    Banco.create(id: 142, codigo:"154", nome: "Caixa Econômica do Estado de Santa Catarina",	sigla: "CEESC");
    Banco.create(id: 143, codigo:"399", nome: "HSBC Bank Brasil",	sigla: "HSBC");
    Banco.create(id: 144, codigo:"255", nome: "Milbanco" ,sigla:	"");
    Banco.create(id: 145, codigo:"151", nome: "Nossa Caixa",	sigla: "BNC");
  end
end
